### ISSUE TITLE
Not catching Legendaries or Mythicals

### ISSUE THREAD

**Issue by G0d-Eater** [Hyperclaw79/PokeBall-SelfBot#71] opened 2018-06-04 01:29 UTC
# Title: The bot does not attempt to catch any legendary or mythical pokemon that spawn.

## Problem:
Whenever a legendary or mythical pokemon spawns the bot just does nothing and does not even attempt to catch it.

## Steps to Reproduce:
This first happened when I left it running for a few hours and went back to check on it and what it all caught, I went through what it caught a what spawned and I noticed that a Phione had spawned a legendary/mythical pokemon and got excited only to see it never tried to catch it and got super bummed. This happened 2 more times sense, the 2nd was when a Jirachi spawned another mythical and I waited at least 30 seconds before spamming again to see if it would try to catch it but it never did, the 3rd time was another Phione and yet again it didn't even try to catch it.

## config.json:

```
{
   "token": "",
   "command_prefix": "P^",
   "priority": [
      "Darkrai", "Mew", "Mewtwo", "Moltres", "Articuno",
	  "Zapdos", "Celebi", "Ho-Oh", "Lugia", "Suicune",
      "Entei", "Raikou", "Metagross", "Regirock", "Regice",
	  "Registeel", "Latias", "Latios", "Kyogre", "Groudon",
	  "Rayquaza", "Jirachi", "Deoxys", "Arceus", "Shaymin",
	  "Manaphy", "Phione", "Cresselia", "Giratina", "Regigigas",
	  "Heatran", "Palkia", "Dialga", "Azelf", "Mesprit",
	  "Uxie", "Genesect", "Meloetta", "Keldeo", "Kyurem",
	  "Landorus", "Zekrom", "Reshiram", "Thundurus", "Tornadus",
	  "Virizion", "Terrakion", "Cobalion", "Volcanion", "Hoopa",
	  "Diancie", "Zygarde", "Yveltal", "Xerneas", "Zeraora",
	  "Blacephalon", "Stakataka", "Marshadow", "Magearna", "Necrozma",
	  "Guzzlord", "Kartana", "Celesteela", "Lunala", "Solgaleo",
	  "Cosmoem", "Cosmog"
   ],
   "avoid": [],
   "catch_rate": 100,
   "delay": 2,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 3,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": false
}
```

## Traceback and Screenshots:

![phione not-caught](https://user-images.githubusercontent.com/22359263/40893954-72ee5fe6-676b-11e8-9d93-6613b6a649b3.JPG)
*At 10:05 am a <b>Phione spawns</b> and the bot <b>does not</b> attempt to catch it*

![next pokemon-caught](https://user-images.githubusercontent.com/22359263/40893958-79b537be-676b-11e8-9aae-8853b6796ff9.JPG)
*At 10:06 am a <b>Buneary spawns</b> and the bot <b>instantly catches it</b> after having completely <b>ignoring</b> the Mythical Phione that spawned 1 minute earlier* 

## Specs.
**OS**: Windows 7 Professional
**Bot Version**: 3.2.2
**Python Version**: 3.6.5

**Comment by Hyperclaw79** [comment] 2018-06-04 11:39
Thank you for the well documented report. I'll look into this immediately. It will be the first priority for today.

I couldn't reproduce this on the premium version, so I'll see where the code might've gone wrong during the update.

Also, you do not have to legendaries to the `priority_list`. They are included by default.

**Comment by Hyperclaw79** [comment] 2018-06-04 13:31
Fixed in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/5daf82fd00567a7a914567f4409644965d2db088.

**Closed by Hyperclaw79** 2018-06-04 13:31 UTC
Labels: bug

**Comment by G0d-Eater** [comment] 2018-06-04 14:53
To update this I just download the zip file again, Extract it, (do I also need to run the setup.bat file again), then I’m good to go?

**Comment by Hyperclaw79** [comment] 2018-06-04 15:11
No need to run `setup.bat` for this one.
Simply replace the `pokeball.py` and `_version.json` and you're good to go.
