### ISSUE TITLE
Buggy Clean_Trash

### ISSUE THREAD

**Issue by 1morekill** [Hyperclaw79/PokeBall-SelfBot#74] opened 2018-06-05 20:47 UTC
I do pokelog before clean_trash and after it finishes the scanning the pokemons, I do clean_trash and it scans again, checks ping. Nothing happens at the end. Is there a trash list or something ? pls help

edit: ive just updated the bot but it releases one and it stops.

**Comment by Hyperclaw79** [comment] 2018-06-06 05:43
Sometimes, pokecord or your bot might lag down. This is usually prominent in the `clean_trash` command.
I will rewrite this function if Miles adds a mass release option.

In your case, it either might be the lag, or it may be the case where the computed duplicates itself are wrong.
After line 535, add a `print(pokes)` to see which is the case.

**Comment by 1morekill** [comment] 2018-06-06 09:27
I tried that code after line 535. First try, I wanted to clean_trash but pokecord didnt answer then checked the ping. Then it stopped. At the second try, it released 15 pokemons. Then checked the pokemon list.

![inked1_li](https://user-images.githubusercontent.com/39968503/41029492-71743cce-6984-11e8-80c5-ac2bc5a2346c.jpg)

After everytime when i try, it shows [ ] this and it says Succesfully cleared the junk. There's too many trash, it doesnt see them i think.

**Comment by Hyperclaw79** [comment] 2018-06-06 09:43
So the problem is with populating the trash list.
Rewriting the mass trasher is a long term goal after Pokecord 3.0 is released. Till then stick to other commands.
I'll leave this issue open but won't be working on it for a while.

**Comment by Hyperclaw79** [comment] 2018-06-13 16:06
Fixed in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/150170291d89ed001fa80d18080a71c44fd7bc0c.

**Closed by Hyperclaw79** 2018-06-13 16:06 UTC
Labels: bug
