### ISSUE TITLE
Not recognizing Pokecord bot and its messages

### ISSUE THREAD

**Issue by VirtueSuzuya** [Hyperclaw79/PokeBall-SelfBot#83] opened 2018-06-13 11:45 UTC
I've had a lot of errors with the bot so I started testing it, i can code python a bit. I was messing around with how it recognizes messages, by having it print something to console if it recognizes the messages. Basic stuff. Anyways the bot can see and react to messages in my guild, and my channel. But it is not recognizing any messages coming from pokecord with embeds. I can send specific screenshots depending on what you need, i'm not exactly sure what to send. Any help would be appreciated thanks

**Comment by Hyperclaw79** [comment] 2018-06-13 13:22
No one faced such issues. Maybe it's some problem with your local end?
Sometimes the `wait_for('message')` itself bugs out and this doesn't necessarily happen for embeds.
But this isn't really an issue as I have workarounds for that placed in. Morever, this doesn't even happen in the public version.
Since you know Python, can you debug it using print statements? On whichever function you are seeing this behavior, add a print(message.embeds[0].to_dict()) below the `wait_for` statements.
Compare that with the pokecord messages in the channel. Post the screenshot for this particular event when the message detection fails. 
It should be reproducible and not a random glitch cause in the latter case, it is beyond my control.

**Comment by VirtueSuzuya** [comment] 2018-06-13 13:48
Oh about the errors with a bot, i didn't mean it as with your bot specifically. Just issues with python install, and other issues like that. I didn't mean for it sound like i was saying it was your bot had a lot of issues. Sorry for coming off that way, i didn't mean to be rude.

I'll work on the debugging and do what you said soon, i'll get back to you. Just wanted to clear that up real quick! Thanks for the help

**Comment by VirtueSuzuya** [comment] 2018-06-13 14:01
Sorry about that, misclick. Anyways I found one apparent issue... and i'm not sure what it is. When I try to run any commands, like the P^Test echo in my testing server this error comes on into the console. It says something about not finding the guild for the message, but i'm definitely doing the command in my discord server and not DMs.

![image](https://user-images.githubusercontent.com/39852200/41355811-5a685742-6ef0-11e8-9f8f-e905a430d3a4.png)

**Comment by Hyperclaw79** [comment] 2018-06-13 14:22
Looks like you must be using a pretty old version of the bot. This was fixed long ago. Please update to the latest version.

**Comment by Hyperclaw79** [comment] 2018-06-13 14:35
It is apparent from your `line number 422` that you are not on the **v3.2.5**.

**Comment by Hyperclaw79** [comment] 2018-06-13 15:55
Closing this as it seems invalid now. Reopen it if you face issues in the latest version.

**Comment by VirtueSuzuya** [comment] 2018-06-13 15:55
okay... 

I downloaded the most recent version, and still it's broken for me. It's now not reading any of my messages, i debugged it using print commands, but now it's not reading any of my messages at all. It has my guild whitelisted, the channel, it's in guild.json. It's logging into my account fine, i'm not really sure what's bothering it. I checked again, and i'm using python 3, aiohttp is downloaded and of course the discord library is. I'm not sure what's bothering it...

**Comment by Hyperclaw79** [comment] 2018-06-13 15:57
Post your `config.json`.

**Comment by VirtueSuzuya** [comment] 2018-06-13 15:57
`{
   "token": "my token goes here",
   "command_prefix": ">",
   "priority": [
      "Groudon",
	    "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 100,
   "delay": 0,
   "delay_on_priority": false,
   "restrict_duplicates": false,
   "max_duplicates": 5,
   "blacklists": [],
   "whitelists": [453772159580635151],
   "blacklist_guilds": [],
   "whitelist_guilds": [450735802973159425],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": true,
   "priority_only": false
}`

**Comment by VirtueSuzuya** [comment] 2018-06-13 15:58
o no idea how to do code on here, here's a hastebin link https://hastebin.com/juyusevuxo.json

**Comment by Hyperclaw79** [comment] 2018-06-13 16:00
First and foremost, add back the default id in the `blacklist_guilds` as it belongs to PokeCord official server.

Apart from that... hmm.. 🤔 The configs look proper.

Wait for a pokemon to spawn and let's see if the autocatcher is working.

**Comment by VirtueSuzuya** [comment] 2018-06-13 16:06
okay it is added back, did not realize that. 

and no it's not
![image](https://user-images.githubusercontent.com/39852200/41363569-3c394954-6f02-11e8-84f7-2cca4341c664.png)

**Comment by VirtueSuzuya** [comment] 2018-06-13 16:10
that again... also i forgot to answer, yes I am using the commands from the same account in which the bot is hosted.

**Comment by Hyperclaw79** [comment] 2018-06-13 16:12
Can you invite me into your server on Discord? I'll try to test my version there with your configs.

**Comment by VirtueSuzuya** [comment] 2018-06-13 16:12
https://discord.gg/FsjaVg

**Closed** 2018-06-13 16:41 UTC
Labels: local

**Comment by Hyperclaw79** [comment] 2018-06-13 16:51
Fixed in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/8525b296774b8b659c782ebe451e0fb84736601c.
