### ISSUE TITLE
invalid control character

### ISSUE THREAD

**Issue by CubeFaces** [Hyperclaw79/PokeBall-SelfBot#68] opened 2018-06-01 15:49 UTC
# Title: invalid control character at:line 2 column 72 (char 73)

## Problem:
I got this error when I tried to run the run.bat file, I'm not sure what exactly that I'm doing wrong

## config.json:
here's the config.json
```
{
   "token": "#########",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 3,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [451368233514172456],
   "autolog": true
}
```

## Traceback and Screenshots:
![](https://cdn.discordapp.com/attachments/306081872243326996/452135182737080341/unknown.png)

## Specs.
**OS**:windows 10 64x
**Bot Version**:3.2.0
**Python Version**:3.6.4

**Comment by Hyperclaw79** [comment] 2018-06-02 00:32
Could you repost your `config.json` along with the starting and ending of your token, while censoring some characters in it?
~~Did you include the `""` in your token?~~
Looks like you included a newline character somewhere... Post a screenshot of your `config,json` instead.
Use some dark color to hide some characters in the token.

**Comment by CubeFaces** [comment] 2018-06-02 18:44
![saved](https://user-images.githubusercontent.com/38924977/40879785-b2727a2e-66a5-11e8-83cc-9f96ce3ce137.png)



here that's my config.json file, and yeah I added the quotes, thanks for responding

**Comment by MateeTheGod** [comment] 2018-06-03 14:18
i am also having trouble with this too

**Comment by Hyperclaw79** [comment] 2018-06-04 11:32
@CubeFaces Try posting your `config.json` contents in [Jsonlint](https://jsonlint.com/) and see if there is any syntax error.

Also, try to reproduce this from another accounts.

Also, since I cannot see your entire token, check this [SO answer](https://stackoverflow.com/questions/9295439/python-json-loads-fails-with-valueerror-invalid-control-character-at-line-1-c) to see if you could fix it on your end.

**Comment by MateeTheGod** [comment] 2018-06-05 06:17
i just reinstalled the program

**Comment by Hyperclaw79** [comment] 2018-06-05 18:22
Since it is a local issue and have not received any word from the OP, I will be closing this for now, assuming it has been fixed.
Feel free to re-open this if need be.

**Closed by Hyperclaw79** 2018-06-05 18:22 UTC
Labels: local, question
